FROM php:8.0.2-fpm

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd

RUN apt-get install -y zlib1g-dev g++ git libicu-dev zip libzip-dev zip curl vim wget bash \
    && docker-php-ext-install intl opcache pdo pdo_mysql \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \ 
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && pecl channel-update pecl.php.net \
    && pecl install apcu

# Set working directory
WORKDIR /var/www/public-tennis-courts-api

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory contents
COPY ./app /var/www/public-tennis-courts-api

# Copy existing application directory permissions
COPY --chown=www:www ./app /var/www/public-tennis-courts-api

# Change current user to www
USER www

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]